better arg parsing

diff --git a/node-deb b/node-deb
--- a/node-deb
+++ b/node-deb
@@ -20,83 +20,123 @@ readlink_() {
 node_deb_dir=`readlink_ $0`
 
 # All the variables that are injected into templates
-node_app=
-node_app_command=
-node_app_version=
-node_binary=
-node_description=
-node_group=
-node_maintainer=
-node_user=
+package_name=
+package_version=
+binary_name=
+start_command=
+user=
+group=
+package_description=
+package_maintainer=
 
 # Other variables
-no_delete=0
+change_log=
+files=
+no_delete_temp=0
+no_md5sums=0
 
-while getopts "b:g:Nu:v:" opt; do
-  case $opt in
-    b)
-      node_binary=$OPTARG
+usage() {
+  # Local var because of grep
+  local helpdoc='HELP'
+  local helpdoc+='DOC'
+  echo 'Usage: node-deb [opts] [-- file1 file2 ...]'
+  echo 'Opts:'
+  grep "$helpdoc" "$node_deb_dir/node-deb" -B 1 | egrep -v '^--$' | sed -e 's/^  //g' -e "s/# $helpdoc: //g"
+}
+
+while [ -n "$1" ]; do
+  param="$1"
+  value="$2"
+  case $param in
+    -b | --binary-name)
+      # HELPDOC: The name of the binary (default: $package-name)
+      binary_name="$value"
+      shift
       ;;
-    g)
-      node_group=$OPTARG
+    -g | --group)
+      # HELPDOC:  The Unix group the process will run as (default: $user)
+      group="$value"
+      shift
       ;;
-    N)
-      no_delete=1
+    -h | --help)
+      # HELPDOC: Display this message and exit
+      usage
+      exit 0
       ;;
-    u)
-      node_user=$OPTARG
+    -n | --package-name)
+      # HELPDOC: The name of the Debian package (default: 'name' from package.json)
+      package_name="$value"
+      shift
       ;;
-    v)
-      node_app_version=$OPTARG
+    --no-delete-temp)
+      # HELPDOC: Do not delete temp directory used to build Debian package
+      no_delete_temp=1
       ;;
-    \?)
-      cat <<-EOF >&2
-			Valid options:
-			-b <binary name> (default app_name)
-			-g <group for user processes run as> (default app_name)
-			-N 'no delete'; do not delete the temporary directory on exit (success or failure)
-			-u <user to run processes as> (default app_name)
-			-v <version> (default 'version' from package.json)
-			EOF
+    --no-md5sums)
+      # HELPDOC: Do not calculate md5sums
+      no_md5sums=1
+      ;;
+    -u | --user)
+      # HELPDOC: The Unix user the process will run as (default: $package-name)
+      user="$value"
+      shift
+      ;;
+    -v | --version)
+      # HELPDOC: The version of the Debian package (default: 'version' from package.json)
+      package_version="$value"
+      shift
+      ;;
+    --)
+      # HELPDOC: Delimiter separating options from files and directories
+      shift
+      break
+      ;;
+    *)
+      echo "Invalid option: $param" >&2
+      usage >&2
       exit 1
-      ;;
   esac
+  shift
 done
 
-shift $(expr $OPTIND - 1)
+if [ -z "$1 " ]; then
+  die 'You must pick at least one directory to add to the Debian package'
+fi
 
-: ${1:?'You must pick at least one directory to add to the Debian package'}
-
-for file_or_dir in "$@"; do
-  if ! [ -e "$file_or_dir" ]; then
-    die "File '$file_or_dir' does not exist. Aborting."
+for file in $files; do
+  if ! [ -e $file ]; then
+    die "File does not exist: '$file'. Aborting"
   fi
 done
 
-node_app=`jq -r '.name' package.json`
-if [ "$node_app" == 'null' ]; then echo 'Your package.json must have element "name"' >&2 && exit 1; fi
-
-node_app_command=`jq -r '.node_deb.start_script' package.json`
-if [ "$node_app_command" == 'null' ]; then echo 'Your package.json must have element "node_deb.start_script"' >&2 && exit 1; fi
-
-if [ -z $node_app_version ]; then
-  node_app_version=`jq -r '.["version"]' package.json`
-  if [ "$node_app_version" == 'null' ]; then echo 'If no override is provided, your package.json must have element "version"' >&2 && exit 1; fi
+package_name=`jq -r '.name' package.json`
+if [ "$package_name" == 'null' ]; then 
+  die 'Your package.json must have element "name"'
 fi
 
-node_description=`jq -r '.["description"]' package.json`
-if [ "$node_description" == 'null' ]; then echo 'Your package.json must have element "description"' >&2 && exit 1; fi
+start_command=`jq -r '.node_deb.start_command' package.json`
+if [ "$start_command" == 'null' ]; then
+  die 'Your package.json must have element "node_deb.start_command"'
+fi
 
-node_maintainer=`jq -r '.["author"]' package.json`
+if [ -z $package_version ]; then
+  package_version=`jq -r '.version' package.json`
+  if [ "$package_version" == 'null' ]; then
+    die 'If no override is provided, your package.json must have element "version"'
+  fi
+fi
 
-: ${node_binary:=$node_app}
-: ${node_group:=$node_app}
-: ${node_user:=$node_app}
+package_description=`jq -r '.description' package.json`
+package_maintainer=`jq -r '.author' package.json`
 
-deb_dir="${node_app}_${node_app_version}_all"
+: ${binary_name:=$package_name}
+: ${user:=$package_name}
+: ${group:=$user}
+
+deb_dir="${package_name}_${package_version}_all"
 
 finish() {
-  if [ $no_delete -ne 1 ]; then
+  if [ $no_delete_temp -ne 1 ]; then
     rm -rf "$deb_dir"
   fi
 }
@@ -106,12 +146,13 @@ trap "finish" EXIT
 if [ -e "$deb_dir" ]; then rm -rf "$deb_dir"; fi
 
 mkdir -p "$deb_dir/DEBIAN"
-mkdir -p "$deb_dir/etc/$node_app"
+mkdir -p "$deb_dir/etc/$package_name"
 mkdir -p "$deb_dir/etc/init"
-mkdir -p "$deb_dir/usr/share/$node_app/bin"
+mkdir -p "$deb_dir/usr/share/$package_name/bin"
 mkdir -p "$deb_dir/usr/bin"
 
 escape() {
+  # TODO ? sed -e 's/[]\/$*.^|[]/\\&/g' <<< "$@"
   echo $(echo $@ | sed -e 's/[]\/$*.^|[]/\\&/g')
 }
 
@@ -119,15 +160,16 @@ replace_vars() {
   local file=$1
   local target_file=$2
 
+  # TODO ? sed < $file \
   cat $file | sed \
-    -e "s/\${node_app}/$(escape $node_app)/g" \
-    -e "s/\${node_app_command}/$(escape $node_app_command)/g" \
-    -e "s/\${node_app_version}/$(escape $node_app_version)/g" \
-    -e "s/\${node_binary}/$(escape $node_binary)/g" \
-    -e "s/\${node_description}/$(escape $node_description)/g" \
-    -e "s/\${node_group}/$(escape $node_group)/g" \
-    -e "s/\${node_maintainer}/$(escape $node_maintainer)/g" \
-    -e "s/\${node_user}/$(escape $node_user)/g" \
+    -e "s/\${node_deb_package_name}/$(escape $package_name)/g" \
+    -e "s/\${node_deb_app_command}/$(escape $app_command)/g" \
+    -e "s/\${node_deb_package_version}/$(escape $package_version)/g" \
+    -e "s/\${node_deb_start_command}/$(escape $start_command)/g" \
+    -e "s/\${node_deb_package_description}/$(escape $package_description)/g" \
+    -e "s/\${node_deb_group}/$(escape $group)/g" \
+    -e "s/\${node_deb_package_maintainer}/$(escape $package_maintainer)/g" \
+    -e "s/\${node_deb_user}/$(escape $user)/g" \
     > $target_file
 }
 
@@ -135,18 +177,18 @@ replace_vars "$node_deb_dir/templates/control" "$deb_dir/DEBIAN/control"
 replace_vars "$node_deb_dir/templates/postinst" "$deb_dir/DEBIAN/postinst"
 replace_vars "$node_deb_dir/templates/postrm" "$deb_dir/DEBIAN/postrm"
 replace_vars "$node_deb_dir/templates/prerm" "$deb_dir/DEBIAN/prerm"
-replace_vars "$node_deb_dir/templates/init.conf" "$deb_dir/etc/init/$node_app.conf"
-replace_vars "$node_deb_dir/templates/binary" "$deb_dir/usr/share/$node_app/bin/$node_binary"
+replace_vars "$node_deb_dir/templates/init.conf" "$deb_dir/etc/init/$package_name.conf"
+replace_vars "$node_deb_dir/templates/binary" "$deb_dir/usr/share/$package_name/bin/$binary_name"
 
-ln -sf "/usr/share/$node_app/bin/$node_binary" "$deb_dir/usr/bin/$node_binary"
+ln -sf "/usr/share/$node_app/bin/$binary_name" "$deb_dir/usr/bin/$binary_name"
 
 chmod -R 0755 "$deb_dir/DEBIAN/"
-chmod -R 0755 "$deb_dir/usr/share/$node_app/bin/$node_binary"
+chmod -R 0755 "$deb_dir/usr/share/$package_name/bin/$binary_name"
 
 # Copy all files into temporary Debian dir
 find "$@" -type f -print0 | {
   while IFS= read -r -d '' file; do
-    dir="$deb_dir/usr/share/$node_app/$(dirname "$file")"
+    dir="$deb_dir/usr/share/$packag_name/$(dirname "$file")"
     if ! [ -e "$dir" ]; then mkdir -p "$dir"; fi
     cp "$file" "$dir"
   done
@@ -172,10 +214,12 @@ write_md5sum() {
 }
 
 # Calculate md5sums
-find "$deb_dir" -path "$deb_dir/DEBIAN" -prune -o -type f -print0 | {
+if [ "$no_md5sums" -eq 0 ]; then
+  find "$deb_dir" -path "$deb_dir/DEBIAN" -prune -o -type f -print0 | {
   while IFS= read -r -d '' file; do
     write_md5sum $file
   done
 }
+fi
 
 dpkg-deb --build "$deb_dir"
