don't fail the install when service doesn't start

diff --git a/templates/postinst b/templates/postinst
--- a/templates/postinst
+++ b/templates/postinst
@@ -54,21 +54,22 @@ start_service () {
 
   if hash service 2> /dev/null; then
     if [[ "$init_type" == 'auto' || "$init_type" == 'upstart' ]]; then
-      service "$service_name" start || die "$service_name could not be registered or started"
+      service "$service_name" start || echo "$service_name could not be registered or started" # using `|| echo` to ensure script exits with 0. Failure to start is not failure to install
     fi
   elif hash start 2> /dev/null; then
     if [[ "$init_type" == 'auto' || "$init_type" == 'upstart' ]]; then
-      start "$service_name" || die "$service_name could not be registered or started"
+      start "$service_name" || echo "$service_name could not be registered or started" # using `|| echo` to ensure script exits with 0. Failure to start is not failure to install
     fi
   elif hash systemctl 2> /dev/null; then
     if [[ "$init_type" == 'auto' || "$init_type" == 'systemd' ]]; then
       {
         systemctl enable "$service_name.service" && \
         systemctl start "$service_name.service"
-      } || die "$service_name could not be registered or started"
+      } || echo "$service_name could not be registered or started" # using `|| echo` to ensure script exits with 0. Failure to start is not failure to install
     fi
   else
-    die 'Your system does not appear to use upstart or systemd, so the service could not be started'
+    # using `echo` to ensure script exits with 0. Failure to start is not failure to install
+    echo 'Your system does not appear to use upstart or systemd, so the service could not be started'
   fi
 }
 
