more init options

diff --git a/templates/postinst b/templates/postinst
--- a/templates/postinst
+++ b/templates/postinst
@@ -49,27 +49,33 @@ start_service () {
   declare -r service_name="$1"
 
   if hash service 2> /dev/null; then
-    service "$service_name" start || echo "${service_name} could not be registered or started"
+    if [[ "$init_type" == 'auto' || "$init_type" == 'upstart' ]]; then
+      service "$service_name" start || echo "${service_name} could not be registered or started"
+    fi
   elif hash start 2> /dev/null; then
-    start "$service_name" || echo "${service_name} could not be registered or started"
+    if [[ "$init_type" == 'auto' || "$init_type" == 'upstart' ]]; then
+      start "$service_name" || echo "${service_name} could not be registered or started"
+    fi
   elif hash systemctl 2> /dev/null; then
-    {
-      systemctl enable "$service_name.service" && \
-      systemctl start "$service_name.service"
-    } || echo "${service_name} could not be registered or started"
+    if [[ "$init_type" == 'auto' || "$init_type" == 'systemd' ]]; then
+      {
+        systemctl enable "$service_name.service" && \
+        systemctl start "$service_name.service"
+      } || echo "${service_name} could not be registered or started"
+    fi
   else
     die 'Your system does not appear to use upstart or systemd, so the service could not be started'
   fi
 }
 
-addGroup {{ node_deb_group }} ''
-addUser {{ node_deb_user }} '' {{ node_deb_group }} '{{ node_deb_user }} user-daemon' '/bin/false'
+addGroup '{{ node_deb_group }}' ''
+addUser '{{ node_deb_user }}' '' '{{ node_deb_group }}' '{{ node_deb_user }} user-daemon' '/bin/false'
 
 if ! [ -d '/var/log/{{ node_deb_package_name }}' ]; then
   mkdir -p '/var/log/{{ node_deb_package_name }}'
 fi
 
-chown {{ node_deb_user }}:{{ node_deb_group }} /var/log/{{ node_deb_package_name }}
+chown '{{ node_deb_user }}:{{ node_deb_group }}' '/var/log/{{ node_deb_package_name }}'
 
 if [[ "$init_type" == 'auto' ]]; then
   start_service '{{ node_deb_package_name }}'
