ported systemd tests to docker
like the upstart tests, these fail because systemctl doesn't play nice

diff --git a/templates/postinst b/templates/postinst
--- a/templates/postinst
+++ b/templates/postinst
@@ -53,25 +53,24 @@ start_service () {
       {
         systemctl enable "$service_name.service" && \
         systemctl start "$service_name.service"
-      } || echo "$service_name could not be registered or started" # using `|| echo` to ensure script exits with 0. Failure to start is not failure to install
+      } || echo "$service_name could not be registered or started"
     fi
   elif hash service 2> /dev/null; then
     if [[ "$init_type" == 'auto' || "$init_type" == 'upstart' || "$init_type" == 'sysv' ]]; then
-      service "$service_name" start || echo "$service_name could not be registered or started" # using `|| echo` to ensure script exits with 0. Failure to start is not failure to install
+      service "$service_name" start || echo "$service_name could not be registered or started"
     fi
   elif hash start 2> /dev/null; then
     if [[ "$init_type" == 'auto' || "$init_type" == 'upstart' ]]; then
-      start "$service_name" || echo "$service_name could not be registered or started" # using `|| echo` to ensure script exits with 0. Failure to start is not failure to install
+      start "$service_name" || echo "$service_name could not be registered or started"
     fi
   elif hash update-rc.d 2> /dev/null; then
     if [[ "$init_type" == 'auto' || "$init_type" == 'sysv' ]]; then
       {
         update-rc.d "$service_name" defaults && \
         "/etc/init.d/$service_name" start
-      } || echo "$service_name could not be registered or started"  # using `|| echo` to ensure script exits with 0. Failure to start is not failure to install
+      } || echo "$service_name could not be registered or started"
     fi
   else
-    # using `echo` to ensure script exits with 0. Failure to start is not failure to install
     echo 'Your system does not appear to use upstart or systemd, so the service could not be started'
   fi
 }
@@ -96,9 +95,8 @@ add_user '{{ node_deb_user }}' '' '{{ node_deb_group }}' '{{ node_deb_user }} us
 npm_install '{{ node_deb_package_name }}'
 
 mkdir -p '/var/log/{{ node_deb_package_name }}'
-
 chown -R '{{ node_deb_user }}:{{ node_deb_group }}' '/var/log/{{ node_deb_package_name }}'
 
-if [[ "$init_type" == 'auto' ]] || [[ "$init_type" == 'systemd' ]] || [[ "$init_type" == 'upstart' ]] || [[ "$init_type" == 'sysv' ]]; then
+if [[ "$init_type" != 'none' ]]; then
   start_service '{{ node_deb_package_name }}'
 fi
